### ISSUE TITLE
Document how to debug addon build steps

### ISSUE THREAD

**Issue by mehulkar** [ember-learn/cli-guides#151]
3 things for debugging that I do that others might find useful:

- `node inspect`
- `DEBUG=*` which is *extremely* noisy, but once you see that and then figure out that it's using the npm `debug` package (or have @bendemboski tell you 😄)
- `npm link` and `isDevelopingAddon() { return true; }`

Documenting these under Advanced Use > Debugging with some examples would be great

cc @jenweber

**Comment by Gaurav0** [comment]
Also how to use broccoli-debug

**Comment by rwjblue** [comment]
> DEBUG=*

I typically use `DEBUG=*,-babel:*` or `DEBUG=ember-cli:*` (reduces a ton of noise).
