### ISSUE TITLE
Investigate if we can improve the output of ember help to lessen the need for document all commands

### ISSUE THREAD

**Issue by jenweber** [ember-learn/cli-guides#160]
#162 proposes expanding some commands guides. The _best_ would be if we didn't need to provide so much info about interpreting the output of `ember help`. This issue tracks suggestions/ideas based on what we find while writing docs.

**Comment by mansona** [comment]
So #162 really did a great job of adding commands to the cli-guides so this issue can be closed now 🎉  we can re-open (or open a new issue) if the need arises again 👍
