### ISSUE TITLE
List out more CLI commands and give more `ember help` guidance

### ISSUE THREAD

**Issue by jenweber** [ember-learn/cli-guides#162]
Community feedback indicates that people need more guidance for using `ember help` and understanding the output, as well as searching for common commands. This is a frequently-requested feature of the CLI guides, so it's a big win if somoene works on this!

We should expand our list of commands and include more `ember help` examples.

To-do:
- Create a new page in the guides called "CLI Commands Reference" under "Advanced"
- Create a list of the commands and options available from `ember --help`
- Make sure whatever you do looks ok in mobile

This is related to #160

Known limitations:
Our Ember-CLI Guides are not versioned. Not all commands and options are available in all versions of Ember/Ember CLI. Rather than do something complicated, we should just show the commands for the latest version of Ember CLI, and a disclaimer that if you are an older version, you should use `ember --help`. An example of something that may not be available is the `-gc` in `ember g component -gc`.

**Comment by mehulkar** [comment]
Instead of trying to come up with a complete list, i'd recommend *removing* everything from the Guides and simply telling people to use `ember help`. Any specific issues should be filed as such.

**Comment by fozy81** [comment]
@jenweber I'm interested to help. I've put together a work in progress PR listing all the commands. But not quite sure exactly what format we are aiming for. Do we want almost a screen dump of `ember --help` or add more description for each command/options :thinking: . Anyway, happy to help, it's a really good learning experience discovering useful commands/options I've not used before :smile: - no matter what form it finally ends up in.

**Comment by jenweber** [comment]
Hi @fozy81, thanks for your help! I think we could start with a screen dump, and if that seems insufficient, that’sa good signal that we need to update the CLI help text as well. We already have a page with longer descriptions for the most common commands, aimed at beginners. So this new page can be more like a reference.

@mehulkar  that was my initial plan for the Guides, but the learning team has received consistent feedback that people are looking for the reference list and they go back to the old site for it. Now that we are redirecting people from the old site, I think we should cover it. I think we still need to emphasize strongly that people should use `help` as their first stop.

**Comment by fozy81** [comment]
Hi @jenweber @mehulkar  I've updated the PR with a screen dump of `ember --help` and added a note to use `ember --help` for the most up to date info/version. It looks okay on mobile, I added line breaks into the ```bash```  output at around 60 characters per line so it fits better on to a small screen without overflowing. 

Does this fulfill the feedback/issue - let me know if anything needs changing or what your reflections on this change are? Do you think there are specific reference page(s) from the old CLI website we need to re-create to fulfill the feedback people have been providing? Perhaps the ember commands table on this [page](https://ember-cli.com/user-guide/#naming-conventions)?

Slightly off topic, one thing that crossed my mind is that the ember guides point new users towards [javascript, html and css](https://guides.emberjs.com/release/getting-started/working-with-html-css-and-javascript/) tutorials/info but it's feasible that our audience 'who knows enough to have built a simple HTML/JavaScript (or JQuery) app' may not be familiar with CLI tools. What do you think about pointing new users towards a CLI tutorial to help gain familiarity with the CLI itself, if required?

**Comment by neojp** [comment]
I have submitted the PR #207 using the [WP-CLI Commands page](https://developer.wordpress.org/cli/commands/) as a reference. It includes the following:

- Added tables of contents with links to each command
- Added anchored headings to each command
- Added description to each command

## Screenshots

![image](https://user-images.githubusercontent.com/127994/97795110-93b60e80-1bd8-11eb-9712-457cf78a9cf4.png)

---

![image](https://user-images.githubusercontent.com/127994/97795123-a3cdee00-1bd8-11eb-98fe-0818e4c3bb50.png)

---

![image](https://user-images.githubusercontent.com/127994/97795125-ad575600-1bd8-11eb-924e-8ec86a89ca9d.png)

**Comment by neojp** [comment]
@jenweber Now that we have merged #207, I have sent a new PR with the remaining `ember generate` blueprints on #208.

Hopefully with this we can finally close this issue.

I'd love to figure out a way to automate this process to avoid this manual process if the documentation for the scripts change, but that could live under a separate issue if we ever get to that.

**Comment by jenweber** [comment]
Thanks everyone for the help! The new page is live with several improvements from multiple people ❤️
