### ISSUE TITLE
Upgrade CLI Guides to Ember Source 3.16

### ISSUE THREAD

**Issue by jayjayjpg** [ember-learn/cli-guides#173]
Part of https://github.com/ember-learn/ember-styleguide/issues/313

**Comment by vinodhrajamuralidharan** [comment]
https://github.com/ember-learn/cli-guides/pull/176

**Comment by jayjayjpg** [comment]
Fixed via @vinodhrajamuralidharan 's work on https://github.com/ember-learn/cli-guides/pull/177 :sparkles:
