### ISSUE TITLE
Create a Staging Demo App for Testing the Website Redesign

### ISSUE THREAD

**Issue by jayjayjpg** [ember-learn/cli-guides#174]
Part of https://github.com/ember-learn/ember-styleguide/issues/313

**Comment by mansona** [comment]
This is already done 🎉 as this is being hosted on Netlify there is a [preview link](https://deploy-preview-141--ember-cli-guides.netlify.app/release/) that is listed at the bottom of the [update PR](https://github.com/ember-learn/cli-guides/pull/141) 👍

**Comment by mansona** [comment]
Actually as the cli-guides is using guidemaker-ember-template, all of the work is likely going to be done in the template project https://github.com/ember-learn/guidemaker-ember-template/pull/30 you can see the demo link at the bottom of that PR 👍
