### ISSUE TITLE
Add section on Naming Conventions to the Folder Layout guide

### ISSUE THREAD

**Issue by jenweber** [ember-learn/cli-guides#200]
In the old guides, we had this page that covers Naming Conventions: https://ember-cli.com/naming-conventions

We need to summarize that content (one paragraph plus examples) and add it to https://cli.emberjs.com/release/basic-use/folder-layout/ The old guide may have outdated information, which you should update for the summary.

**Comment by maxwondercorn** [comment]
I started working on a PR for this
