### ISSUE TITLE
Need to reorganize / edit "Managing Dependencies" section

### ISSUE THREAD

**Issue by Gaurav0** [ember-learn/cli-guides#21]
I don't think this belongs in "writing addons" because this is mostly about importing and customizing dependencies which can either be done in the app via ember-cli-build.js or in the addon via index.js. How exactly it should be organized probably deserves further discussion on discord. There is a discussion about this on Discord here: https://discordapp.com/channels/480462759797063690/480777444203429888/499943437626507274

See also my review here: https://github.com/ember-learn/cli-guides-source/pull/19#pullrequestreview-163829777

**Comment by BradenLawrence** [comment]
Thanks for reviewing and adding this issue! I can pick up a few of the items you called out:
- "Mention it will use yarn when there is both a yarn.lock and a package-lock.json"
- "It should be not recommended to use bower. It is not officially deprecated, but it should be."
- "but does not watch node_modules."
I'll add any followup questions inline with your review.

**Comment by jenweber** [comment]
Proposed breakdown:

Basic Use - Importing Assets
Advanced Use - Managing Dependencies
Writing Addons - Including Assets In Addons

Copied from Gaurav's comments on https://github.com/ember-learn/cli-guides-source/pull/24

**Comment by jenweber** [comment]
Closed by #40
