### ISSUE TITLE
Update ember-cli-uglify references and configuration

### ISSUE THREAD

**Issue by Windvis** [ember-learn/cli-guides#216]
ember-cli-uglify was renamed to ember-cli-terser and [included in the 3.21.1 release](https://github.com/ember-cli/ember-cli/releases/tag/v3.21.1). However, the cli docs [still reference ember-cli-uglify ](https://github.com/ember-learn/cli-guides/search?q=uglify).

**Comment by rwjblue** [comment]
Ya, thanks for reporting definitely should get this fixed up.

I think we just need to fix these two locations:

https://github.com/ember-learn/cli-guides/blob/fe580fb1fc322345c83cfc8f478b06269f2675ed/guides/advanced-use/index.md

https://github.com/ember-learn/cli-guides/blob/fe580fb1fc322345c83cfc8f478b06269f2675ed/guides/advanced-use/asset-compilation.md

Definitely would love a PR for this!

**Comment by Windvis** [comment]
I'll try to take a look when I find some time in the coming evenings. :+1:
