### ISSUE TITLE
add recomendation to use wsl 2 on windows

### ISSUE THREAD

**Issue by yaxinr** [ember-learn/cli-guides#219]
[use of wsl 2](https://stackoverflow.com/a/66481419/1359764) give x10 faster speed compilation.
many programmers hate to use emberjs because of slow compilation and recompilation on windows.

**Comment by ijlee2** [comment]
Hi, @yaxinr. Thank you for suggesting a solution to improve the developer experience of Windows users. I think it's a good idea to provide the solution in https://cli.emberjs.com/release/appendix/windows/.

I briefly looked at the StackOverflow answer. My initial impression was that the answer is a bit short and may be lacking details for new users of `wsl 2`. (I haven't used Windows in some time, so I wasn't sure if I would be able to follow the steps easily.)

What do you think about creating a pull request that updates the `appendix/windows` page, and provides a paragraph or two that explains what `wsl 2` is and how to install it for Ember development? I think that could help us get a conversation started.

If you have questions about how we can update the `appendix/windows` page, feel free to let us know. Thanks again!
