### ISSUE TITLE
Fastboot not rendering line numbers for code snippets?

### ISSUE THREAD

**Issue by marcoow** [ember-learn/cli-guides#240]
I just realized that FastBoot doesn't seem to be rendering line numbers for code snippets so those only pop-in when re-rendering the snippet client-side:

https://user-images.githubusercontent.com/1510/139454559-7b262e2c-59ab-4283-9ef4-dc8deb483e22.mov

**Comment by IgnaceMaes** [comment]
This is fixed with the introduction of `ember-showdown-shiki`.

https://github.com/ember-learn/cli-guides/pull/316
