### ISSUE TITLE
Using TailwindCSS with Ember

### ISSUE THREAD

**Issue by maxwondercorn** [ember-learn/cli-guides#244]
Document best practice(s) for integrating/using TailwindCSS with Ember.

Issue based on Discord discussion re: difficulty in setting up/integrating TailwindCSS. Using PostCSS ([chrism/emberjs-tailwind-purgecss](https://github.com/chrism/emberjs-tailwind-purgecssl)) has been default method.  Alternative and potentially simpler methods are now available with Tailwind's JIT mode and CLI.

This would be a good appendix topic.

cc: @NullVoxPopuli

**Comment by NullVoxPopuli** [comment]
I'll PR this later this week, thank you!!
