### ISSUE TITLE
"How to deploy" link to official tutorial no longer exists

### ISSUE THREAD

**Issue by hugopeixoto** [ember-learn/cli-guides#257]
In [How to deploy](https://cli.emberjs.com/release/basic-use/deploying/#howtodeploy), there's the following paragraph:

> For a tutorial that shows how to build your app and upload it to a web host using `scp` and `rsync`, see the [Official Ember.js Tutorial](https://guides.emberjs.com/release/tutorial/deploying/)

The official tutorial has since been rewritten and no longer contains instructions on how to deploy ember apps.The quick start section contains a section on how to deploy to netlify, though: https://guides.emberjs.com/release/getting-started/quick-start/#toc_deploying-your-app-to-netlify

Since the official tutorial no longer mentions this, maybe the whole paragraph should be removed?

**Comment by jenweber** [comment]
Yes, that seems good to do.

Either that or there might be another deploying section in the guides we can link to.

**Comment by hugopeixoto** [comment]
> Either that or there might be another deploying section in the guides we can link to.

I didn't find any. Couldn't find any issues planning to create one either, but I might have missed it.

I'll make a PR removing this paragraph
