### ISSUE TITLE
404 on https://cli.emberjs.com/

### ISSUE THREAD

**Issue by laurmurclar** [ember-learn/cli-guides#266]
Noticed when trying to get to the CLI Guides from the main Ember guides. 

To reproduce:
1. Simply open https://cli.emberjs.com/

or -
1. Go to https://guides.emberjs.com/
3. Open `Docs > CLI Guides` from dropdown in nav bar (Redirects you to https://cli.emberjs.com/)
4. Observe 404

This is the link mentioned in the homepage of this repo also so I assume it's still relevant and shouldn't be 404ing 😄

**Comment by jenweber** [comment]
Hello! Fixing this now. Thank you for reporting.

Root cause: https://github.com/ember-learn/cli-guides/pull/267

**Comment by jenweber** [comment]
Fixed! Additionally, the Node version was set to 14 in the NODE_VERSION env variables for Netlify. I set it to 12 and rebuilt.

This is a temporary strategy. We need to get on Node 14 ASAP.

**Comment by laurmurclar** [comment]
Thanks for fixing it so quickly Jen!
