### ISSUE TITLE
Quest - draft new content for the cli docs

### ISSUE THREAD

**Issue by jenweber** [ember-learn/cli-guides#32]
Issue #3 brings us to MVP. Here's the plan for what comes after. Our goal is to empower new addon authors.

- [ ] write a second addon authoring tutorial. It can focus on wrapping an existing library.
- [x] finish reviewing and revising legacy content
- [ ] cover common configurations
- [ ] link to or import some pieces of Broccoli docs
- [ ] ???

**Comment by locks** [comment]
@jenweber can this be closed?
