### ISSUE TITLE
Include some documentation about pods

### ISSUE THREAD

**Issue by jenweber** [ember-learn/cli-guides#43]
So, a ton of people use pods but we don't really cover it well anywhere, along the lines of "what are pods" and "how do they work."

I think maybe this content should go in the Appendix or Advanced sections.

**Comment by maxwondercorn** [comment]
They may be more to add later, but there's now pods info under project layouts.  I must have forgotten to included resolve issue #43 in the PR

**Comment by Gaurav0** [comment]
Fixed with #56
