### ISSUE TITLE
Spellcheck or lint for common mistakes

### ISSUE THREAD

**Issue by jenweber** [ember-learn/cli-guides#61]
It would be helpful to have a test/linting for the following:

- "JavaScript"
- "Ember"
- "Ember.js"
- "npm"

**Comment by maxwondercorn** [comment]
remark is part of [unified](https://unified.js.org) and there is a remark plugin to use [retext](https://github.com/retextjs/retext).  retext has spellchecking.  I haven't done it, but there is way of configuring the plugins to work together.  I believe the same npm `lint:md` script would do it all.

This would be different than the other guide repos but it could be an experiment.  If it works here, it could be used to standardize/add more consistency across all guides.

I can plug away 😬 at this sometime next week, if you like
