### ISSUE TITLE
Addon project structure

### ISSUE THREAD

**Issue by ppcano** [ember-learn/cli-guides#84]
The previous ember-cli guide shows more information regarding the conventions of the addon structure.

- [previous](https://ember-cli.com/extending/#addon-project-structure)

- [latest](https://cli.emberjs.com/release/writing-addons/#addonfilestructure)

When looking at ember-cli/ember-cli#8342, I wanted to know how `test-support` and `addon-test-support` works, but this info is not available in the new ember-cli guide.

I think the missing info should be added in the new guides as well. I can create a PR if someone suggests how it could fit best in the new guide structure. 

Some suggestions to start the discussion: 

- add the missing items into the `Addon file structure` section.

- create an `Extended addon file structure` section.

cc @jenweber

**Comment by jenweber** [comment]
I am closing this issue because the file structure will likely change with [V2 addons](https://rfcs.emberjs.com/id/0507-embroider-v2-package-format).
