### ISSUE TITLE
Convert Component invocation examples into Angle Brackets notation

### ISSUE THREAD

**Issue by jenweber** [ember-learn/cli-guides#86]
@cah-danmonroe has volunteered to help do this!

Part of work for https://github.com/ember-learn/guides-source/issues/139

**Comment by cah-danmonroe** [comment]
I'm on it...

**Comment by maxwondercorn** [comment]
#87 was merged so this issue can be closed

**Comment by jenweber** [comment]
Closed by a merged PR
