### ISSUE TITLE
`devDependencies` vs `dependencies` in addons.

### ISSUE THREAD

**Issue by ppcano** [ember-learn/cli-guides#98]
https://github.com/ember-decorators/ember-decorators/issues/134#issuecomment-317098014

> Ember-CLI considers `dependencies` in an addon to actually be addon dependencies, and `devDependencies` to be the Dummy app's dependencies.

This case looks to be the same than having to set `ember-cli-htmlbars` in the `dependencies` for component addons.

It may be good to document this detail when talking about the `Dummy` app.

**Comment by rwjblue** [comment]
Some additional info for someone willing to pick this up (from [this discord convo](https://discordapp.com/channels/480462759797063690/485861149821239298/548249164224397312) between @nathanhammond and myself):

```
in an addon:

* the dummy app is the project
* the addon is made to seem like a dependency of the project
* the top level package.json's dependencies are "Dependencies of the addon"
* the top level package.json's devDepdnencies are "dependencies of the project" aka peers of the addon being developed
```

**Comment by maxwondercorn** [comment]
I can take a shot at this over the weekend

**Comment by jenweber** [comment]
Awesome, thank you :) I've been PR-ing some of this info into READMEs of addons that are useful to put inside other addons, and we really need it in the base learning materials.
